### ISSUE TITLE
yaml emitter doesn't know what to do with numpy types

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#156]
It seems fairly likely folks will leak numpy types into the graph. And this should not cause problems, but it currently does because the YAML libraries do the wrong thing.

E.g. using the pyaml-style yaml emitter.
```python
import demes
import numpy as np

x = np.full(shape=55, fill_value=1000)
g = demes.Graph(description="test", time_units="generations")
g.deme("A", initial_size=x[0])
demes.dump(g, "/dev/stdout")
```

```yaml
demes:
- end_time: 0
  id: A
  initial_size: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args: [i8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    6AMAAAAAAAA=
```

The situation is not improved by using the newer ruamel API.
```python
import sys
import demes
import numpy as np
import ruamel.yaml

x = np.full(shape=55, fill_value=1000)
g = demes.Graph(description="test", time_units="generations")
g.deme("A", initial_size=x[0])
data = g.asdict_simplified()
yaml = ruamel.yaml.YAML()
yaml.dump(data, sys.stdout)
```
Which gives an error message from hell (`cannot represent an object: 1000`!).
```
Traceback (most recent call last):
  File "/tmp/np.py", line 15, in <module>
    yaml.dump(data, sys.stdout)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/main.py", line 451, in dump
    return self.dump_all([data], stream, _kw, transform=transform)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/main.py", line 465, in dump_all
    self._context_manager.dump(data)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/main.py", line 817, in dump
    self._yaml.representer.represent(data)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 96, in represent
    node = self.represent_data(data)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 123, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 371, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 1017, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 123, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 361, in represent_list
    return self.represent_sequence(u'tag:yaml.org,2002:seq', data)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 933, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 123, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 371, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 1017, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 133, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/grg/.local/lib/python3.8/site-packages/ruamel/yaml/representer.py", line 404, in represent_undefined
    raise RepresenterError('cannot represent an object: %s' % (data,))
ruamel.yaml.representer.RepresenterError: cannot represent an object: 1000
```

Note that the json emitter has no such qualms about numpy types, and gracefully outputs values based on `isinstance(value, int)` or `isinstance(value, float)`.

**Comment by jeromekelleher** [comment]
Ugh. It's probably simplest to force coercion to Python types when we assign them to the objects in the Graph. Can we do this reasonably gracefully using attrs?

**Comment by grahamgower** [comment]
Yeah, that's probably a good approach. I've been thinking about adding more runtime type checking anyway, and using attrs converters is probably a flexible way of getting both birds with the one stone.

**Comment by grahamgower** [comment]
I've changed my mind on using converters. If we have, e.g. `converter=float` for an attrib, then we'll also convert yaml strings to floats, including `inf` and [many others](https://stackoverflow.com/a/20929881/9500949) that aren't numerical types in yaml.

There's another simple solution avilable though, which uses a recently added arg of `attr.asdict()` to call a custom serialisation function.

**Comment by jeromekelleher** [comment]
Yes, it is annoying how lenient ``int`` and ``float`` are sometimes, good call.
