### ISSUE TITLE
anaconda and ruamel_yaml vs  ruamel.yaml trouble with demes

### ISSUE THREAD

**Issue by pbeerli** [popsim-consortium/demes-python#229]
I tried to install demes; this a macbook pro 13" 2020 [M1 chip] running Macos 11.2.1 with an updated anaconda version. 
Installing demes works;
but running 'import demes' fails see below 

the remedy is to install ruamel.yaml despite the claim that is present [btw the snippet below is a recreation after uninstalling demes and ruamel.yaml -- the error messages are the same as I encountered them in the original install]
[there is discussion about ruamel_yaml vs ruamel.yaml on the web but no clear solution]

Install log:
```
=======
cornelius:beerli>pip install demes --upgrade --pre
Collecting demes
  Using cached demes-0.1.0a3-py3-none-any.whl (26 kB)
Requirement already satisfied: ruamel.yaml>=0.15.78 in /opt/homebrew/anaconda3/lib/python3.8/site-packages (from demes) (0.15.87)
Requirement already satisfied: attrs>=20.3.0 in /opt/homebrew/anaconda3/lib/python3.8/site-packages (from demes) (20.3.0)
Installing collected packages: demes
Successfully installed demes-0.1.0a3
cornelius:beerli>python -c 'import demes'         
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/demes/__init__.py", line 25, in <module>
    from .load_dump import load_asdict, loads_asdict, load, loads, dump, dumps
  File "/opt/homebrew/anaconda3/lib/python3.8/site-packages/demes/load_dump.py", line 8, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel.yaml'
cornelius:beerli>conda install ruamel.yaml     
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/anaconda3

  added / updated specs:
    - ruamel.yaml


The following NEW packages will be INSTALLED:

  ruamel.yaml        pkgs/main/osx-64::ruamel.yaml-0.16.12-py38haf1e3a3_1
  ruamel.yaml.clib   pkgs/main/osx-64::ruamel.yaml.clib-0.2.2-py38haf1e3a3_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
cornelius:beerli>python -c 'import demes' 
# success! import does not complain!
```

**Comment by molpopgen** [comment]
Thanks for the report.  This is quite odd--I cannot reproduce with pip in a fresh venv on Linux.

I don't quite follow what you mean about `ruamel_yaml` vs `ruamel.yaml`.  The former isn't in the error messages you posted?

**Comment by molpopgen** [comment]
I can reproduce in a fresh Miniconda3 install on Linux.  It seems that this package is there by "default", but is somehow not importable/

Very odd:

```
which pip
/home/condauser/miniconda3/bin/pip
(base) condauser@pop-os:~$ pip install --upgrade ruamel-yaml
Collecting ruamel-yaml
  Using cached ruamel.yaml-0.16.12-py2.py3-none-any.whl (111 kB)
Requirement already satisfied, skipping upgrade: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in ./miniconda3/lib/python3.8/site-packages (from ruamel-yaml) (0.2.2)
Installing collected packages: ruamel-yaml
  Attempting uninstall: ruamel-yaml
    Found existing installation: ruamel-yaml 0.15.87
ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

The fix is `conda install ruamel.yaml`, just like @pbeerli stated.

This appears to be a conda-specific problem.  Long term, it may be up to the conda recipe to somehow fix this.  It means the recipe will definitely need an import  test!

**Comment by grahamgower** [comment]
I can't seem to reproduce this with a fresh miniconda3 environment (conda `4.9.2`, which installed pip `20.0.1`). What version of conda are you using? I see an old (fixed) conda bug that may be relevant here: https://docs.conda.io/projects/conda/en/latest/release-notes.html#id155

**Comment by jeromekelleher** [comment]
> Long term, it may be up to the conda recipe to somehow fix this. It means the recipe will definitely need an import test!

We'll definitely want a conda recipe, and +1 on the import test. I'll do this once we have a non-alpha version on pip.

**Comment by molpopgen** [comment]
> What version of conda are you using?

I reproduced it with:

```
conda --version
conda 4.9.2
(base) condauser@pop-os:~$ pip --version
pip 20.2.4 from /home/condauser/miniconda3/lib/python3.8/site-packages/pip (python 3.8)
(base)
```

This is a Miniconda that I downloaded yesterday just to check this issue.

**Comment by molpopgen** [comment]
> an old (fixed) conda bug

The link is [this](https://github.com/conda/conda/issues/7672) and it seems to be updating to the latest ruamel API.

**Comment by grahamgower** [comment]
I still can't reproduce this (on Linux). Are you sure there's not something else contaminating the environment? Maybe from your `$HOME/.local/lib/python3.8`, or the base conda environment?

```sh
t490:~ $ conda --version
conda 4.9.2

t490:~ $ cat ~/.condarc
auto_activate_base: false
channels:
  - conda-forge
  - defaults

t490:~ $ conda create -n demes "python=3.8"
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/grg/miniconda3/envs/demes

  added / updated specs:
    - python=3.8


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.12.5-ha878542_0
  certifi            conda-forge/linux-64::certifi-2020.12.5-py38h578d9bd_1
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.35.1-hea4e1c9_2
  libffi             conda-forge/linux-64::libffi-3.3-h58526e2_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h2828fa1_18
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h2828fa1_18
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h6de172a_18
  ncurses            conda-forge/linux-64::ncurses-6.2-h58526e2_4
  openssl            conda-forge/linux-64::openssl-1.1.1j-h7f98852_0
  pip                conda-forge/noarch::pip-21.0.1-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.8.8-hffdb5ce_0_cpython
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  readline           conda-forge/linux-64::readline-8.0-he28a2e2_2
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py38h578d9bd_3
  sqlite             conda-forge/linux-64::sqlite-3.34.0-h74cdb3f_0
  tk                 conda-forge/linux-64::tk-8.6.10-h21135ba_1
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1010


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate demes
#
# To deactivate an active environment, use
#
#     $ conda deactivate

t490:~ $ conda activate demes
(demes) t490:~ $ pip --version
pip 21.0.1 from /home/grg/miniconda3/envs/demes/lib/python3.8/site-packages/pip (python 3.8)
(demes) t490:~ $ pip show demes
WARNING: Package(s) not found: demes
(demes) t490:~ $ pip show ruamel.yaml
WARNING: Package(s) not found: ruamel.yaml
(demes) t490:~ $ pip show ruamel_yaml
WARNING: Package(s) not found: ruamel_yaml
(demes) t490:~ $ pip show ruamel-yaml
WARNING: Package(s) not found: ruamel-yaml
(demes) t490:~ $ pip install demes
Collecting demes
  Using cached demes-0.1.0a3-py3-none-any.whl (26 kB)
Collecting ruamel.yaml>=0.15.78
  Using cached ruamel.yaml-0.16.12-py2.py3-none-any.whl (111 kB)
Collecting attrs>=20.3.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting ruamel.yaml.clib>=0.1.2
  Using cached ruamel.yaml.clib-0.2.2-cp38-cp38-manylinux1_x86_64.whl (578 kB)
Installing collected packages: ruamel.yaml.clib, ruamel.yaml, attrs, demes
Successfully installed attrs-20.3.0 demes-0.1.0a3 ruamel.yaml-0.16.12 ruamel.yaml.clib-0.2.2
(demes) t490:~ $ python -c "import demes"
(demes) t490:~ $ python -c "import ruamel.yaml as yaml; print(yaml.__file__)"
/home/grg/miniconda3/envs/demes/lib/python3.8/site-packages/ruamel/yaml/__init__.py
```

And trying with `pip 20.2.4`:
```sh
(demes) t490:~ $ pip install pip==20.2.4
Collecting pip==20.2.4
  Using cached pip-20.2.4-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.0.1
    Uninstalling pip-21.0.1:
      Successfully uninstalled pip-21.0.1
Successfully installed pip-20.2.4

(demes) t490:~ $ pip uninstall demes ruamel.yaml
Found existing installation: demes 0.1.0a3
Uninstalling demes-0.1.0a3:
  Would remove:
    /home/grg/miniconda3/envs/demes/bin/demes
    /home/grg/miniconda3/envs/demes/lib/python3.8/site-packages/demes-0.1.0a3.dist-info/*
    /home/grg/miniconda3/envs/demes/lib/python3.8/site-packages/demes/*
Proceed (y/n)? y
  Successfully uninstalled demes-0.1.0a3
Found existing installation: ruamel.yaml 0.16.12
Uninstalling ruamel.yaml-0.16.12:
  Would remove:
    /home/grg/miniconda3/envs/demes/lib/python3.8/site-packages/ruamel.yaml-0.16.12-py3.8-nspkg.pth
    /home/grg/miniconda3/envs/demes/lib/python3.8/site-packages/ruamel.yaml-0.16.12.dist-info/*
    /home/grg/miniconda3/envs/demes/lib/python3.8/site-packages/ruamel/yaml/*
Proceed (y/n)? y
  Successfully uninstalled ruamel.yaml-0.16.12

(demes) t490:~ $ pip install demes
Collecting demes
  Using cached demes-0.1.0a3-py3-none-any.whl (26 kB)
Requirement already satisfied: attrs>=20.3.0 in ./miniconda3/envs/demes/lib/python3.8/site-packages (from demes) (20.3.0)
Collecting ruamel.yaml>=0.15.78
  Using cached ruamel.yaml-0.16.12-py2.py3-none-any.whl (111 kB)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in ./miniconda3/envs/demes/lib/python3.8/site-packages (from ruamel.yaml>=0.15.78->demes) (0.2.2)
Installing collected packages: ruamel.yaml, demes
Successfully installed demes-0.1.0a3 ruamel.yaml-0.16.12
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/home/grg/miniconda3/envs/demes/bin/python3.8 -m pip install --upgrade pip' command.
(demes) t490:~ $ python -c "import demes"
(demes) t490:~ $ python -c "import ruamel.yaml as yaml; print(yaml.__file__)"
/home/grg/miniconda3/envs/demes/lib/python3.8/site-packages/ruamel/yaml/__init__.py
```

**Comment by molpopgen** [comment]
> the base conda environment

This is the problem.  demes can't be installed in the base env.  I'm assuming this is what the OP was trying.

**Comment by molpopgen** [comment]
> Are you sure there's not something else contaminating the environment?

Yes, I'm sure.  I only ever use conda in a user account that I first wipe clean.

**Comment by grahamgower** [comment]
I don't think the conda base environment is a usable environment. I've had numerous problems with package clashes when I first tried using conda, and have never used the base environment since. But maybe there's a constructive way to solve this anyhow, other than saying "don't do that"?

**Comment by molpopgen** [comment]
I've never seen anything like this before.  I don't use conda much, though.

**Comment by grahamgower** [comment]
Hi @pbeerli. We now have a conda package for `demes` on conda-forge. Could you try this and let us know if you still have problems?

**Comment by pbeerli** [comment]
well, I had no problems after that reinstall of ruamel; but conda install demes works fine.
