### ISSUE TITLE
yaml loader doesn't accept "Infinity" string.

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#394]
The CLI parses input files with `demes.load_all(..., format="yaml")` (yaml is a superset of json afterall). But it fails due to Infinity strings.

```json
{
  "time_units": "generations",
  "demes": [
    {
      "name": "a",
      "start_time": "Infinity",
      "epochs": [
        {
          "start_size": 1
        }
      ]
    }
  ]
}
```

```
$ python -m demes /tmp/inf.json
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/grg/src/demes/demes-python/demes/__main__.py", line 216, in <module>
    cli()
  File "/home/grg/src/demes/demes-python/demes/__main__.py", line 212, in cli
    args.func(args)
  File "/home/grg/src/demes/demes-python/demes/__main__.py", line 91, in __call__
    num_documents, graphs = self.load_and_count_documents(args.filename)
  File "/home/grg/src/demes/demes-python/demes/__main__.py", line 130, in load_and_count_documents
    for graph in graph_generator:
  File "/home/grg/src/demes/demes-python/demes/load_dump.py", line 239, in load_all
    yield demes.Graph.fromdict(data)
  File "/home/grg/src/demes/demes-python/demes/demes.py", line 2006, in fromdict
    deme = graph._add_deme(
  File "/home/grg/src/demes/demes-python/demes/demes.py", line 1486, in _add_deme
    if len(ancestors) == 0 and not math.isinf(start_time):
TypeError: must be real number, not str
```

**Comment by apragsdale** [comment]
Oh no, did I miss this case? Sorry this wasn't caught before.
